# Generated by Django 4.1.5 on 2023-01-31 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="accounts", name="groups",),
        migrations.RemoveField(model_name="accounts", name="is_superuser",),
        migrations.RemoveField(model_name="accounts", name="user_permissions",),
    ]
